### ISSUE TITLE
Redesign para melhorar o uso

### ISSUE THREAD

**Issue by JoaoCarabetta** [GEEEdu/materias_edu#1]
Levanto alguns tópicos que podem melhorar o uso:

- [ ] Título, Cabeçalho
- [ ] Fotter
- [ ] Background e cores
- [ ] Melhorar cores e disposição dos dias da semana
- [ ] Aumentar e centralizar barra de busca

**Comment by Fbrufino** [comment]
Opa! Sim sim, a versão que taí era só pra estabelecer as funcionalidades básicas e mostrar pras outras pessoas pra decidir se eu levava pra frente -- o que obviamente foi melhor do que eu esperava xD --, mas agora já tá na hora de fazer o texto e acabar o layout.

Pontos específicos:
**Rodapé:** No fim, provavelmente vai ter um pro site inteiro, mas seria bom termos um plano B pro caso de ficarmos mesmo que provisoriamente em domínio separado ou pra usar de base se o site do grupo ficar sem;
**Controles da tabela:** As cores da grade horária eu deixei as primeiras que não ficaram horríveis, por mim os bg poderiam ser mais claros, assim como a fonte cinza. A disposição, se for entre os itens da grade, só tem que tomar o cuidado de deixar ok pra mobile tb, a versão atual desse site tá boazinha nesse caso. Em geral eu tenho uma terceira versão de cabeçalho na cabeça que conseguiria contemplar minha preferência pela centralização, não exibir todos os controles logo de cara, mas ainda deixar "implicitamente clara" a função de filtrar por horário, que é um dos diferenciais em relação ao Júpiter. Se tiver fazendo um modelo me avisa pq eu nem começo a fazer daí! Outra coisa válida pra barra de busca é confirmar se os dois gatilhos que tão lá bastam (tem um gatilho específico pra colagem no default do Datatables que ficou de fora do mvp, por exemplo)

**Comment by Fbrufino** [comment]
Opa! No fim das contas, a ferramenta vai ficar dentro do site mesmo. Adaptar o projeto vai envolver operação no front-end e um pouco tb no back-end pra integrá-los ao site do grupo, sendo que o design do EconoEduc já está posto para referência. Falando meio por cima o que tem que fazer: retirar o background, checar as dimensões dos divs, cores, fontes, inserir a info de autoria da ferramenta (tipo assinatura de matéria de jornal), linkar pro github, configurar as exceções no tema do WP pra receber as funcionalidades da página.

Amanhã (ou hoje, dia 17, pras pessoas normais haha) pretendo incorporar o progresso do branch daqui no master, fechar esse issue e criar outro issue+branch para a adaptação ao site -- não é estritamente necessário, mas acho que fica melhor organizado.
